Imports System.Data
Imports System.Data.OleDb
Imports System.Data.Odbc
Imports System.Data.DataTable
Imports System.Data.SqlClient

Public Class reservationfrm
    Private bitmap As Bitmap 'for print grid
    Dim rdr As SqlDataReader
    Dim colColors As Collection = New Collection 'for color of listbox
    Dim provider As String  'for access and sql same
    Dim dataFile As String  'for access and sql same
    Dim connString As String   'for access and sql same
    ' Dim myConnection As OleDbConnection = New OleDbConnection   'for access replace it  Dim myConnection As SqlConnection = New SqlConnection
    Dim myConnection As SqlConnection = New SqlConnection
    Dim ds As DataSet = New DataSet            'for access and sql same
    ' Dim da As OleDbDataAdapter                'for access replace it with Dim da As SqlDataAdapter
    Dim da As SqlDataAdapter
    Dim tables As DataTableCollection = ds.Tables  'for access and sql same
    Dim source1 As New BindingSource()                    'for access and sql same
    Dim source2 As New BindingSource()
    Dim con As New SqlClient.SqlConnection                      'for sql
    Dim cmd As New SqlClient.SqlCommand                        'for sql

    Dim dt As New DataTable
    Dim cs As String = "Data Source=GEO;Initial Catalog=mainclinicdb;Integrated Security=True"
    Private Sub dbaccessconnection()

        Try
            con.ConnectionString = cs
            cmd.Connection = con
           
        Catch ex As Exception
            MsgBox("DataBase not connected due to the reason because " & ex.Message)
            Me.Dispose()
        End Try
    End Sub
    Private Sub insert()
        dbaccessconnection()
        con.Open()
        cmd.CommandText = "insert into tbl_reservation(R_Entryno,Re_id,Rate_ID,Service_Name,Gender,Service_Description,Member_ID,Memebr_name,m_contactinfo,m_age,m_address,Reservation_Date,Reservation_Time,R_Date,Reservation_Status)values('" & reentry_txt.Text & "','" & resid_txt.Text & "','" & rid_txt.Text & "','" & rese_sertxt.Text & "','" & re_gendrtxt.Text & "','" & re_serdescriptiontxt.Text & "','" & mid_txt.Text & "','" & re_mname_txt.Text & "','" & re_membercntct_txt.Text & "','" & re_memberage_txt.Text & "','" & re_memberadress_txt.Text & "','" & dte_txt.Value & "','" & rese_time.Value & "','" & reservedon_txt.Value & "','" & pending_txt.Text & "')"
        cmd.ExecuteNonQuery()
        Label4.Text = "'" & re_mname_txt.Text & "' reserve details saved successfully!"
        con.Close()
    End Sub
    Private Sub getdata()
        Dim con As New SqlConnection(cs)
        con.Open()
        Dim da As New SqlDataAdapter("Select R_Entryno,Re_id,Rate_ID,Service_Name,Gender,Service_Description,Member_ID,Memebr_name,m_contactinfo as [Contact Number],m_age as [Age],m_address as [Address],Reservation_Date,Reservation_Time,R_Date from tbl_reservation ", con)
        Dim dt As New DataTable
        da.Fill(dt)
        source2.DataSource = dt
        get_reservationdata.DataSource = dt
        get_reservationdata.Refresh()
    End Sub
    Private Sub reservationfrm_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        dbaccessconnection()
        getdata()
        txtboxid()
        autogenerated()
        RateID_FillCombo()
        M_ID_FillCombo()
        Me.Label11.Text = Format(Now, "yyyy-MM-dd")
        Me.Label31.Text = TimeOfDay.ToString("h:mm:ss tt")
        getdata_reservation()
    End Sub

    Private Sub svemem_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles svemem.Click
        insert()

    End Sub
    Private Sub s_nameadd()
        rese_sertxt.Text &= rese_sertxtt.Text & ","
    End Sub
   
    Private Sub txtboxid()
        Try
            dbaccessconnection()
            con.Open()
            Dim num As New Integer
            cmd.CommandText = "SELECT MAX(R_Entryno) FROM tbl_reservation"
            If (IsDBNull(cmd.ExecuteScalar)) Then
                num = 1
                reentry_txt.Text = num.ToString
            Else

                num = cmd.ExecuteScalar + 1
                reentry_txt.Text = num.ToString
            End If
            con.Close()
        Catch ex As Exception
            MsgBox("Error" & ex.Message)
            Me.Dispose()
        End Try

    End Sub
    Private Sub autogenerated()

        Dim curValue As Integer
        Dim result As String
        Using con As SqlConnection = New SqlConnection(cs)
            con.Open()
            Dim cmd = New SqlCommand("select Max(Re_id) from tbl_reservation", con)
            result = cmd.ExecuteScalar().ToString()
            If String.IsNullOrEmpty(result) Then
                result = "RES-0000"
            End If

            result = result.Substring(3)
            Int32.TryParse(result, curValue)
            curValue = curValue + 1
            result = "IN" + curValue.ToString("D4")
            resid_txt.Text = result
        End Using
    End Sub
    Private Sub RateID_FillCombo()
        Try
            Dim conn As New System.Data.SqlClient.SqlConnection(cs)
            Dim strSQL As String = "SELECT Rate_ID FROM tbl_services"
            Dim da As New System.Data.SqlClient.SqlDataAdapter(strSQL, conn)
            Dim ds As New DataSet
            da.Fill(ds, "tbl_services")
            With Me.rid_txt
                .DataSource = ds.Tables("tbl_services")
                .DisplayMember = "Rate_ID"
                .ValueMember = "Rate_ID"
                .SelectedIndex = -1
                .AutoCompleteMode = AutoCompleteMode.SuggestAppend
                .AutoCompleteSource = AutoCompleteSource.ListItems
            End With


        Catch ex As Exception
            MessageBox.Show(" Error while retriving data" & ex.Message)
        End Try

    End Sub
    Private Sub rid_txt_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rid_txt.SelectedIndexChanged

        Dim str As String = cs
        Dim con As SqlConnection = New SqlConnection(str)
        Dim query As String = "select * from tbl_services where Rate_ID = '" & rid_txt.Text & "' "
        Dim cmd As SqlCommand = New SqlCommand(query, con)
        Dim dbr As SqlDataReader
        Try

            con.Open()
            dbr = cmd.ExecuteReader()
            If dbr.Read() Then
                rese_sertxtt.Text = dbr.GetValue(2)
                re_gendrtxt.Text = dbr.GetValue(3)
                re_serdescriptiontxt.Text = dbr.GetValue(6)


            End If
            re_gendrtxt.Visible = True
            re_serdescriptiontxt.Visible = True
            Label18.Visible = True
            Label20.Visible = True

        Catch ex As Exception
            MessageBox.Show("At least one entry", "", MessageBoxButtons.OK, MessageBoxIcon.Exclamation)
        End Try
    End Sub
    Private Sub M_ID_FillCombo()
        Try
            Dim conn As New System.Data.SqlClient.SqlConnection(cs)
            Dim strSQL As String = "SELECT M_ID FROM tbl_memberreg"
            Dim da As New System.Data.SqlClient.SqlDataAdapter(strSQL, conn)
            Dim ds As New DataSet
            da.Fill(ds, "tbl_memberreg")
            With Me.mid_txt
                .DataSource = ds.Tables("tbl_memberreg")
                .DisplayMember = "M_ID"
                .ValueMember = "M_ID"
                .SelectedIndex = -1
                .AutoCompleteMode = AutoCompleteMode.SuggestAppend
                .AutoCompleteSource = AutoCompleteSource.ListItems
            End With


        Catch ex As Exception
            MessageBox.Show(" Error while retriving data" & ex.Message)
        End Try

    End Sub
    Private Sub mid_txt_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles mid_txt.SelectedIndexChanged
        Dim str As String = cs
        Dim con As SqlConnection = New SqlConnection(str)
        Dim query As String = "select * from tbl_memberreg where M_ID = '" & mid_txt.Text & "' "
        Dim cmd As SqlCommand = New SqlCommand(query, con)
        Dim dbr As SqlDataReader
        Try

            con.Open()
            dbr = cmd.ExecuteReader()
            If dbr.Read() Then
                re_mname_txt.Text = dbr.GetValue(2)
                re_membercntct_txt.Text = dbr.GetValue(3)
                re_memberage_txt.Text = dbr.GetValue(4)

                re_memberadress_txt.Text = dbr.GetValue(6)


            End If
            re_mname_txt.Visible = True
            re_membercntct_txt.Visible = True
            re_memberage_txt.Visible = True

            re_memberadress_txt.Visible = True

            Label17.Visible = True
            Label16.Visible = True
            Label14.Visible = True

            Label12.Visible = True

        Catch ex As Exception
            MessageBox.Show("At least one entry", "", MessageBoxButtons.OK, MessageBoxIcon.Exclamation)
        End Try
    End Sub
    Private Sub clear()
        Try

            rid_txt.Text = ""
            mid_txt.Text = ""
            

        Catch ex As Exception
            MsgBox("Error:Some thing is going wrong,Close application and try again")
        End Try
    End Sub
    Private Sub Btnadd_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Btnadd.Click
        Clear()

        ' getdata()
        txtboxid()
        autogenerated()
        RateID_FillCombo()
        M_ID_FillCombo()
    End Sub
    Private Sub edit()
        con.Close()
        Try
            dbaccessconnection()
            con.Open()
            TabControl1.SelectedTab = TabPage2
            cmd.CommandText = ("UPDATE tbl_reservation SET  R_Entryno= '" & reentry_txt.Text & "', Re_id= '" & resid_txt.Text & "',Rate_ID= '" & rid_txt.Text & "',Service_Name= '" & rese_sertxt.Text & "',Gender= '" & re_gendrtxt.Text & "',Service_Description= '" & re_serdescriptiontxt.Text & "',Member_ID= '" & mid_txt.Text & "',Memebr_name= '" & re_mname_txt.Text & "',m_contactinfo= '" & re_membercntct_txt.Text & "',m_age= '" & re_memberage_txt.Text & "',m_address= '" & re_memberadress_txt.Text & "',Reservation_Date= '" & dte_txt.Value & "',Reservation_Time= '" & rese_time.Value & "',R_Date= '" & reservedon_txt.Value & "' where R_Entryno=" & reentry_txt.Text & "")
            cmd.ExecuteNonQuery()
            Label4.Text = "Product details updated successfully!"
            con.Close()
        Catch ex As Exception
            MessageBox.Show("Data Not Updated")
        End Try

     
    End Sub
    Private Sub btnupdte_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnupdte.Click
        edit()
        getdata()
    End Sub

    Private Sub Btndel_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Btndel.Click
        TabControl1.SelectedTab = TabPage2
    End Sub

 

   
    Private Sub DeleteSelecedRows()
        Dim ObjConnection As New SqlConnection()
        Dim i As Integer
        Dim mResult
        mResult = MsgBox("Want you really delete the selected records?", _
        vbYesNo + vbQuestion, "Removal confirmation")
        If mResult = vbNo Then
            Exit Sub
        End If
        ObjConnection.ConnectionString = cs
        Dim ObjCommand As New SqlCommand()
        ObjCommand.Connection = ObjConnection
        For i = Me.get_reservationdata.SelectedRows.Count - 1 To 0 Step -1
            ObjCommand.CommandText = "delete from tbl_reservation where R_Entryno='" & get_reservationdata.SelectedRows(i).Cells("R_Entryno").Value & "'"
            ObjConnection.Open()
            ObjCommand.ExecuteNonQuery()
            ObjConnection.Close()
            Me.get_reservationdata.Rows.Remove(Me.get_reservationdata.SelectedRows(i))
        Next

    End Sub
    Private Sub Button6_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Button6.Click
        DeleteSelecedRows()
    End Sub
    Private Sub Button1_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Button1.Click
        s_nameadd()
    End Sub

   
  
    Private Sub get_reservationdata_CellContentClick_1(ByVal sender As System.Object, ByVal e As System.Windows.Forms.DataGridViewCellEventArgs) Handles get_reservationdata.CellContentClick
        TabControl1.SelectedTab = TabPage1
        svemem.Enabled = False
        Btndel.Enabled = True
        btnupdte.Enabled = True
        re_gendrtxt.Visible = True
        re_serdescriptiontxt.Visible = True
        Label18.Visible = True
        Label20.Visible = True
        Label17.Visible = True
        Label16.Visible = True
        Label14.Visible = True

        Label12.Visible = True
        Try

            Btndel.Enabled = True
            btnupdte.Enabled = True

            Me.reentry_txt.Text = get_reservationdata.CurrentRow.Cells(0).Value.ToString
            Me.resid_txt.Text = get_reservationdata.CurrentRow.Cells(1).Value.ToString
            Me.rid_txt.Text = get_reservationdata.CurrentRow.Cells(2).Value.ToString
            Me.rese_sertxt.Text = get_reservationdata.CurrentRow.Cells(3).Value.ToString
            Me.rese_sertxtt.Text = get_reservationdata.CurrentRow.Cells(3).Value.ToString
            Me.re_gendrtxt.Text = get_reservationdata.CurrentRow.Cells(4).Value.ToString
            Me.re_serdescriptiontxt.Text = get_reservationdata.CurrentRow.Cells(5).Value.ToString
            Me.mid_txt.Text = get_reservationdata.CurrentRow.Cells(6).Value.ToString
            Me.re_mname_txt.Text = get_reservationdata.CurrentRow.Cells(7).Value.ToString
            Me.re_membercntct_txt.Text = get_reservationdata.CurrentRow.Cells(8).Value.ToString
            Me.re_memberage_txt.Text = get_reservationdata.CurrentRow.Cells(9).Value.ToString

            Me.re_memberadress_txt.Text = get_reservationdata.CurrentRow.Cells(10).Value.ToString
            Me.dte_txt.Value = get_reservationdata.CurrentRow.Cells(11).Value.ToString
            Me.rese_time.Text = get_reservationdata.CurrentRow.Cells(12).Value.ToString
            Me.reservedon_txt.Text = get_reservationdata.CurrentRow.Cells(13).Value.ToString

        Catch ex As Exception
            MessageBox.Show(ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error)
        End Try
    End Sub

    Private Sub Button12_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Button12.Click
        Me.Dispose()
    End Sub
 
   
    Private Sub getdata_reservation()
        'yyyy/MM/dd

        Dim con As New SqlConnection(cs)
        con.Open()
        Dim da As New SqlDataAdapter("Select Top 20 R_Entryno,Memebr_name,Reservation_Date,Reservation_Time,Reservation_Served_EndTime,Serve_Emplyee,Reservation_Status From tbl_reservation where Reservation_Date = '" & Label11.Text & "'", con)
        Dim dt As New DataTable
        da.Fill(dt)
        source2.DataSource = dt
        DataGridView1.DataSource = dt
        DataGridView1.Refresh()
    End Sub
    Private Sub client_search_txt()
        Dim str As String
        Try
            con.Open()
            str = "Select R_Entryno,Memebr_name,Reservation_Date,Reservation_Time,Reservation_Status from tbl_reservation where Memebr_name like '" & TextBox3.Text & "%' and Reservation_Date = '" & Label11.Text & "'"
            cmd = New SqlCommand(str, con)
            da = New SqlDataAdapter(cmd)
            ds = New DataSet
            da.Fill(ds, "tbl_reservation")
            con.Close()
            DataGridView1.DataSource = ds
            DataGridView1.DataMember = "tbl_reservation"
            DataGridView1.Visible = True
        Catch ex As Exception
            MsgBox(ex.Message)
        End Try
    End Sub

    Private Sub TextBox3_TextChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles TextBox3.TextChanged
        client_search_txt()
    End Sub
    ' check reservation of today
    Private Sub getdata_pending_reservation()
        'yyyy/MM/dd
        Dim con As New SqlConnection(cs)
        con.Open()
        Dim da As New SqlDataAdapter("Select Top 20 R_Entryno,Memebr_name,Reservation_Date,Reservation_Time,Reservation_Status From tbl_reservation where Reservation_Date = '" & Label11.Text & "' And Reservation_Status ='Pending'", con)
        Dim dt As New DataTable
        da.Fill(dt)
        source2.DataSource = dt
        DataGridView1.DataSource = dt
        DataGridView1.Refresh()
    End Sub
   
    Private Sub refreshstatus()
        con.Close()
        Try
            dbaccessconnection()
            con.Open()
            cmd.CommandText = ("UPDATE tbl_reservation SET Serve_Emplyee= '" & today_employeeadd_txt.Text & "',Reservation_Status='" & today_Cstatus.Text & "',Reservation_Served_EndTime='" & DateTimePicker1.Value & "' where R_Entryno=" & today_entry.Text & "")
            cmd.ExecuteNonQuery()
            MessageBox.Show("Status Updated")
            ' Label10.Text = "St details updated successfully!"
            con.Close()
        Catch ex As Exception
            MessageBox.Show("Data Not Updated" & ex.Message)
        End Try
    End Sub
    Private Sub Button3_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Button3.Click
        refreshstatus()
        getdata_reservation()
    End Sub
    Private Sub getdata_served_reservation()
        'yyyy/MM/dd
        Dim con As New SqlConnection(cs)
        con.Open()
        Dim da As New SqlDataAdapter("Select Top 20 R_Entryno,Memebr_name,Reservation_Date,Reservation_Time,Reservation_Served_EndTime,Reservation_Status From tbl_reservation where Reservation_Date = '" & Label11.Text & "' And Reservation_Status ='Served'", con)
        Dim dt As New DataTable
        da.Fill(dt)
        source2.DataSource = dt
        DataGridView1.DataSource = dt
        DataGridView1.Refresh()
    End Sub
    Private Sub getdata_serving_reservation()
        'yyyy/MM/dd
        Dim con As New SqlConnection(cs)
        con.Open()
        Dim da As New SqlDataAdapter("Select Top 20 R_Entryno,Memebr_name,Reservation_Date,Reservation_Time,Reservation_Served_EndTime,Serve_Emplyee,Reservation_Status From tbl_reservation where Reservation_Date = '" & Label11.Text & "' And Reservation_Status ='Serving'", con)
        Dim dt As New DataTable
        da.Fill(dt)
        source2.DataSource = dt
        DataGridView1.DataSource = dt
        DataGridView1.Refresh()
    End Sub
    Private Sub getdata_cancelled_reservation()
        'yyyy/MM/dd
        Dim con As New SqlConnection(cs)
        con.Open()
        Dim da As New SqlDataAdapter("Select Top 20 R_Entryno,Memebr_name,Reservation_Date,Reservation_Time,Reservation_Status From tbl_reservation where Reservation_Date = '" & Label11.Text & "' And Reservation_Status ='Cancelled'", con)
        Dim dt As New DataTable
        da.Fill(dt)
        source2.DataSource = dt
        DataGridView1.DataSource = dt
        DataGridView1.Refresh()
    End Sub

    Private Sub RadioButton1_CheckedChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles RadioButton1.CheckedChanged
        getdata_pending_reservation()
    End Sub

    Private Sub RadioButton2_CheckedChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles RadioButton2.CheckedChanged
        getdata_served_reservation()
    End Sub

    Private Sub RadioButton3_CheckedChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles RadioButton3.CheckedChanged
        getdata_serving_reservation()
    End Sub

    Private Sub RadioButton4_CheckedChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles RadioButton4.CheckedChanged
        getdata_cancelled_reservation()
    End Sub
    Private Sub Check_employee()
        Dim str As String
        'AND Reservation_Date = '" & Label11.Text & "'   And Reservation_Status ='Serving'"
        Try
            con.Open()
            str = "Select R_Entryno,Memebr_name,Reservation_Time,Reservation_Served_EndTime,Serve_Emplyee,Reservation_Status from tbl_reservation where Serve_Emplyee like '" & today_employeeadd_txt.Text & "%'  And Reservation_Time BETWEEN '" & today_Ctime.Text & "' AND '" & Label31.Text & "'  And Reservation_Status ='Serving' AND Reservation_Date = '" & Label11.Text & "'"
            cmd = New SqlCommand(str, con)
            da = New SqlDataAdapter(cmd)
            ds = New DataSet
            da.Fill(ds, "tbl_reservation")
            con.Close()
            DataGridView1.DataSource = ds
            DataGridView1.DataMember = "tbl_reservation"
            DataGridView1.Visible = True
        Catch ex As Exception
            MsgBox(ex.Message)
        End Try
        If (DataGridView1.Rows.Count = 0) Then
            Me.Label33.Text = "Available"
        Else
            Me.Label33.Text = "Not Available"
            Button3.Enabled = False
        End If
    End Sub

    Private Sub today_employeeadd_txt_Validated(ByVal sender As Object, ByVal e As System.EventArgs) Handles today_employeeadd_txt.Validated
        Check_employee()
    End Sub


    Private Sub today_Cname_TextChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles today_Cname.TextChanged

    End Sub

    Private Sub today_Cname_Validated(ByVal sender As Object, ByVal e As System.EventArgs) Handles today_Cname.Validated

    End Sub

    Private Sub today_Cname_Validating(ByVal sender As Object, ByVal e As System.ComponentModel.CancelEventArgs) Handles today_Cname.Validating
        Dim strsql As String = "select R_Entryno,Memebr_name,Reservation_Date,Reservation_Time,Reservation_Served_EndTime,Serve_Emplyee,Reservation_Status from tbl_reservation where Memebr_name like('" + today_Cname.Text + "%')"
        Dim strcon As String = cs
        Dim odapre As New SqlDataAdapter(strsql, strcon)
        Dim datTable As New DataTable
        Dim incount As Integer
        odapre.Fill(datTable)
        For incount = 0 To datTable.Rows.Count - 1
            today_entry.Text = datTable.Rows(incount)("R_Entryno").ToString
            today_Cdate.Text = datTable.Rows(incount)("Reservation_Date").ToString
            today_Ctime.Text = datTable.Rows(incount)("Reservation_Time").ToString
            today_Cstatus.Text = datTable.Rows(incount)("Reservation_Status").ToString
            today_employeeadd_txt.Text = datTable.Rows(incount)("Serve_Emplyee").ToString
            DateTimePicker1.Text = datTable.Rows(incount)("Reservation_Served_EndTime").ToString
            ' DateofBirthDateTimePicker.Text = datTable.Rows(incount)("DateofBirth").ToString
            ' EmailaddressTextBox.Text = datTable.Rows(incount)("Emailaddress").ToString
            ' PicturesPictureBox1. = datTable.Rows(incount)("Pictures")
        Next
    End Sub


   
    Private Sub Button4_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Button4.Click
        today_entry.Text = ""
        today_Cstatus.Text = ""
        today_employeeadd_txt.Text = ""
        today_entry.Text = ""
        Button3.Enabled = True

    End Sub

    Private Sub Button5_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Button5.Click
        ratesfrm.Show()
    End Sub

   

    Private Sub rese_sertxtt_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles rese_sertxtt.SelectedIndexChanged

    End Sub

    Private Sub rese_sertxtt_TextChanged(ByVal sender As Object, ByVal e As System.EventArgs) Handles rese_sertxtt.TextChanged
        s_nameadd()
    End Sub
End Class